version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: imeji
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg-data:
